### ISSUE TITLE
Add support for structured LABELs

### ISSUE THREAD

**Issue by pombredanne** [nexB/conan#11]
See http://label-schema.org/ and  an example here https://github.com/CentOS/sig-cloud-instance-images/blob/45cccc8f40650e860852cfe9054eefa5a4c0dc54/docker/Dockerfile

**Comment by mjherzog** [comment]
label-schema has been deprecated in favor of https://github.com/opencontainers/image-spec
See: https://label-schema.org/rc1/

**Comment by pombredanne** [comment]
Some examples:
```
labels:
      org.opencontainers.image.url: https://github.com/docker/scout-cli-plugin
      org.opencontainers.image.title: scout-cli-plugin
      org.opencontainers.image.source: https://github.com/docker/scout-cli-plugin
      org.opencontainers.image.created: '2025-08-29T06:33:02.944Z'
      org.opencontainers.image.version: 1.18.4
      org.opencontainers.image.licenses:
      org.opencontainers.image.revision: e686e77ac91e69a42d42cb1e2b2d47deba2739d6
      com.docker.image.source.entrypoint: Dockerfile
      org.opencontainers.image.description: Docker Scout CLI Plugin
```
